using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ETrade.Entities.Enums
{
    public enum MethodList
    {
        None,
        AddressAdd,
        AddressDelete,
        AddressUpdate,
        AddressList,
        BrandAdd,
        BrandDelete,
        BrandUpdate,
        BrandList,
        CategoryAdd,
        CategoryDelete,
        CategoryUpdate,
        CategoryList,
        CommentAdd,
        CommentDelete,
        CommentUpdate,
        CommentList,
        CountryAdd,
        CountryDelete,
        CountryUpdate,
        CountryList,
        CurrencyAdd,
        CurrencyDelete,
        CurrencyUpdate,
        CurrencyList,
        GenderAdd,
        GenderDelete,
        GenderUpdate,
        GenderList,
        IdentityAdd,
        IdentityDelete,
        IdentityUpdate,
        IdentityList,
        MediaAdd,
        MediaDelete,
        MediaUpdate,
        MediaList,
        ProductAdd,
        ProductDelete,
        ProductUpdate,
        ProductList,
        RoleAdd,
        RoleDelete,
        RoleUpdate,
        RoleList,
        RoleUserAdd,
        RoleUserDelete,
        RoleUserUpdate,
        RoleUserList,
        UserAdd,
        UserDelete,
        UserUpdate,
        UserList,
    }
}
